apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: booquiz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ${DOCKER_USERNAME}/booquiz-backend:${DOCKER_TAG}
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets