name: Frontend Pipeline

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      DOCKER_TAG:
        required: true
      KUBE_CONFIG:
        required: true

jobs:
  frontend:
    runs-on: ubuntu-latest
    environment: ${{'prod'}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test frontend
        run: |
          npm install -g pnpm
          pnpm install --no-frozen-lockfile
          cd apps/frontend && pnpm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/booquiz-frontend:${{ secrets.DOCKER_TAG }}

      - name: Set up kubeconfig
        uses: ./.github/actions/setup-k8s
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy
        run: |
          export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          export DOCKER_TAG=${{ secrets.DOCKER_TAG }}
          envsubst < k8s/base/frontend/deployment.yaml | kubectl apply -f -
          kubectl rollout restart deployment/frontend -n booquiz